routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController');
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::middleware(['is_admin'])->group(function () {
	Route::prefix('dashboard')->group(function () {
		Route::get('/', 'DashboardController')->name('dashboard');

		// User Routes
		Route::get('/users/{user}/restore', 'UserController@restore')->name('users.restore');
		Route::get('/users/{users}/harddelete', 'UserController@harddelete')->name('users.hard.delete');
		Route::get('/users/switch', 'UserController@switch')->name('users.switch');
		Route::get('/users/archive', 'UserController@archive')->name('users.archive');
		Route::resource('/users', 'UserController');

		//Category Routes
		Route::get('/category/{category}/restore', 'CategoryController@restore')->name('category.restore');
		Route::get('/category/{category}/harddelete', 'CategoryController@harddelete')->name('category.hard.delete');
		Route::get('/category/rank', 'CategoryController@rank')->name('category.rank');
		Route::get('/category/switch', 'CategoryController@switch')->name('category.switch');
		Route::get('/category/archive', 'CategoryController@archive')->name('category.archive');
		Route::resource('/category', 'CategoryController');

        //Menu Routes
		Route::get('/menu/{menu}/restore', 'MenuController@restore')->name('menu.restore');
		Route::get('/menu/{menu}/harddelete', 'MenuController@harddelete')->name('menu.hard.delete');
		Route::get('/menu/archive', 'MenuController@archive')->name('menu.archive');
		Route::get('/menu/rank', 'MenuController@rank')->name('menu.rank');
		Route::get('/menu/switch', 'MenuController@switch')->name('menu.switch');
		Route::resource('/menu', 'MenuController');

		// Product Routes
		Route::get('/product/restore', 'ProductController@restore')->name('product.restore');
		Route::get('/product/harddelete', 'ProductController@harddelete')->name('product.harddelete');
		Route::get('/product/rank', 'ProductController@rank')->name('product.rank');
		Route::get('/product/switch', 'ProductController@switch')->name('product.switch');
		Route::get('/product/product', 'ProductController@archive')->name('product.archive');
		Route::resource('/product', 'ProductController');

	});
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Category extends Model
{
	use SoftDeletes;

	protected $fillable = [
		'name',
		'description',
		'parent',
		'slug',
		'status',
	];
	
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Category;
use App\Http\Requests\Category\Store;
use App\Http\Requests\Category\Update;

class CategoryController extends Controller
{

    public function __construct(){

        view()->share('categories', Category::orderBy('rank', 'ASC')->get());
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {

        return view('dashboard.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {

        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Store $request) {

        Category::create($request->validated());
        return redirect()->route('category.index')->withNotify('Category created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category){

        return view('dashboard.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category){

        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Update $request, Category $category) {

     $category->update($request->all());
     return redirect()->route('category.edit', $category->id)->withNotify('Category updated.');
 }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category) {

        $category->delete();
        return redirect()->route('category.index')->withNotify('Category archived.');
    }

    public function switch(Request $request){

        $category   = Category::findOrFail($request->id);
        $category->status = $request->status=='true' ? 1 : 0;
        $category->update();
    }


    public function rank(Request $request){

     foreach ($request->get('ord') as $key => $value) {

       Category::where(['id' => $value])->update(['rank' => $key]);
   }
}

public function archive(){

    $categories = Category::onlyTrashed()->orderBy('rank', 'ASC')->get();
    return view('dashboard.categories.archive',compact('categories'));
}

public function restore($id){

    $category=Category::onlyTrashed()->findOrFail($id);
    $category->restore();
    return redirect()->route('category.archive')->withNotify('Category restored.');
}

public function harddelete($id){

 Category::onlyTrashed()->findOrFail($id)->forceDelete();
 return redirect()->route('category.archive')->withNotify('Category deleted.');
}

}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __invoke()
    {
        return view('dashboard.index');
    }
}

resources/views/dashboard/categories/archive.blade.php
@extends('dashboard.layouts.master')
@section('page', 'Silinmiş Kategoriler')
@section('content')


<div class="card rounded-0">
    <div class="card-header d-flex align-items-center">
        <h3 class="card-title">{{'Tabloda '.count($categories).' kategori bulundu'}}
        </h3>
        <div class="clearfix"></div>
        <hr>
        <a href="{{route('category.index')}}" class="btn btn-info rounded-0 mr-2"><i class="fas fa-eye mr-1"></i>Tüm Kategoriler</a>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive">
        <table id="example1" class="table  table-hover">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                    <th>Created At</th>
                    <th>Deleted At</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>

                @if(count($categories)>0)
                @php $i=1; @endphp

                @foreach($categories as $category)

                <tr>
                    <td>{{$i++}}</td>
                    <td>{{$category->name}}</td>
                    <td>{{$category->created_at->diffForHumans()}}</td>
                    <td>{{$category->updated_at->diffForHumans()}}</td>

                    <td>
                     <span class="text-danger">Deleted</span>
                 </td>


                 <td>
                    <a title="geri yükle" href="{{route('category.restore',$category->id)}}" class="btn btn-sm btn-success "><i class="fas fa-recycle"></i>
                    </a>

                    <a title="sil" href="{{route('category.hard.delete',$category->id)}}" class="btn btn-sm btn-danger deletebtn "><i class="fas fa-trash-alt"></i>
                    </a>

                </td>
            </tr>

            @endforeach

            @else

            @endif

        </tbody>
    </table>
</div>
<!-- /.card-body -->
</div>
@endsection
@push('css')
<link rel="stylesheet" href="{{@asset('/plugins')}}/datatables-bs4/css/dataTables.bootstrap4.css">
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{@asset('/plugins')}}/sweetalert2/sweetalert2.min.css">

@endpush
@push('js')
<script src="{{@asset('/plugins')}}/datatables/jquery.dataTables.js"></script>
<script src="{{@asset('/plugins')}}/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<script src="{{@asset('/plugins')}}/sweetalert2/sweetalert2.min.js"></script>

<script>
    $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });  

    });

    $(function(){
     $('.switch').change(function() {
        var $id     = $(this).attr('id');
        var status = $(this).prop('checked');

        $.get("{{route('category.switch')}}",{status:status,id:$id}, function(response){});

    });



 });

    $(".deletebtn").on("click", function(event){

     event.preventDefault();

     var data_url = $(this).attr("href");

     Swal.fire({
        title: 'Gerçekten Silmek İstiyormusunuz ? ',
        text: "Bu işlemi geri alamazsınız!",
        type: 'error',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Evet, Sil',
        cancelButtonText :  'Hayır'     
    }).then((result) => {
        if (result.value) {
            window.location.href = data_url;
        }
    })
});

</script>
@endpush

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Horizontal Form</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="{{route('category.store')}}" class="form-horizontal" method="POST">
        @csrf

        <div class="card-body">

            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input name="name" type="text" class="form-control" id="name" placeholder="Name"
                    value="{{old('name')}}">
                </div>
            </div>
<div class="form-group row">
                <label for="parent" class="col-sm-2 col-form-label">Parent</label>
                <div class="col-sm-10">
                   <select class="form-control" name="parent" id="parent">
                    <option value="0">Üst Kategori Seçiniz</option>
                    @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
            

        <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                <textarea class="form-control" rows="4" name="description" id="description" rows="4"></textarea>
            </div>
        </div>

    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        <button type="submit" class="btn btn-info">Create</button>
       <a href="{{route('category.index')}}" type="button" class="btn btn-default float-right">Cancel</a>
    </div>
    <!-- /.card-footer -->
</form>
</div>

@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Horizontal Form</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="{{route('category.update',$category->id)}}" class="form-horizontal" method="POST">
        @csrf
        @method('PUT')

        <div class="card-body">


            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input name="name" type="text" class="form-control" id="name"
                    value="{{$category->name}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="parent" class="col-sm-2 col-form-label">Parent</label>
                <div class="col-sm-10">
                 <select class="form-control" name="parent" id="parent">
                    <option  <?php echo $category->parent==0 ? 'selected' : ''?> value="0">Üst Kategori</option>
                    @foreach($categories as $allcategory)
                    <option <?php echo  $category->parent==$allcategory->id ? 'selected' : ''?> value="{{$allcategory->id}}" >{{$allcategory->name}}</option>
                    @endforeach

                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                <textarea name="description" type="text" class="form-control" id="description"
                value="">{{$category->description}}</textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="parent" class="col-sm-2 col-form-label">Durum</label>
            <div class="col-sm-10">
             <select class="form-control" name="status" id="status">
                <option value="0" <?php echo $category->status==0 ? 'selected' : ''?> >Pasif</option>
                <option value="1" <?php echo $category->status==1 ? 'selected' : ''?> >Aktif</option>

            </select>
        </div>
    </div>


</div>
<!-- /.card-body -->
<div class="card-footer">
    <button type="submit" class="btn btn-info">Update</button>
    <a href="{{route('category.index')}}" type="button" class="btn btn-default float-right">Cancel</a>
</div>
<!-- /.card-footer -->
</form>
</div>

@endsection

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.master')
@section('page', 'Kategoriler')
@section('content')


<div class="card rounded-0">
    <div class="card-header d-flex align-items-center">
        <h3 class="card-title">{{'Tabloda '.count($categories).' kategori bulundu'}}
        </h3>
        <div class="clearfix"></div>
        <hr>
        <a href="{{route('category.create')}}" class="btn btn-primary rounded-0 mr-2"><i class="fas fa-plus mr-1"></i>Create</a>
        <a href="{{route('category.archive')}}" class="btn btn-danger rounded-0"><i class="fas fa-file-archive mr-1"></i>Archives</a>

    </div>

    <!-- /.card-header -->
    <div class="card-body table-responsive">
        <table id="example1" class="table  table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody id="sortable">

                @if(count($categories)>0)

                @foreach($categories as $category)

                <tr id="ord-{{$category->id}}">
                 <td style="cursor:move" class="handle"><i class="fas fa-arrows-alt-v"></i></td>
                 <td>{{$category->name}}</td>
                 <td>{{$category->created_at->diffForHumans()}}</td>
                 <td>{{$category->updated_at->diffForHumans()}}</td>

                 <td>
                    <input class="switch" id="{{$category->id}}" type="checkbox" <?php echo $category->status==1 ? 'checked' : ''  ?>  data-toggle="toggle" data-on="Aktif" data-off="Pasif" data-onstyle="success" data-offstyle="danger" data-size="sm">
                </td>


                <td class="d-flex align-items-center d-md-block">

                 <a href="{{route('category.show',$category->id)}}" class="btn btn-sm btn-warning text-white"><i class="fas fa-eye"></i>
                 </a>
                 <a  href="{{route('category.edit',$category->id)}}"  class="btn btn-sm btn-success"><i class="fas fa-edit"></i>

                 </a>

                 <form method="POST" action="{{route('category.destroy', $category->id) }}" class="d-inline-block"> @csrf                                     
                    @method('DELETE')                                    
                    <button type="submit" class="btn btn-sm btn-danger"> <i class="fas fa-trash-alt"></i>
                    </button> 
                </form>

            </td>
        </tr>

        @endforeach

        @else

        @endif

    </tbody>
</table>
</div>
<!-- /.card-body -->
</div>
@endsection
@push('css')
<link rel="stylesheet" href="/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
@endpush
@push('js')
<script src="/plugins/datatables/jquery.dataTables.js"></script>
<script src="/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });  

    });

    $(function(){
       $('.switch').change(function() {
        var $id     = $(this).attr('id');
        var status = $(this).prop('checked');

        $.get("{{route('category.switch')}}",{status:status,id:$id}, function(response){});

    });

       $('#sortable').sortable({
        handle: '.handle',
        animation: 150,
        update:function(){
            var rank = $('#sortable').sortable('serialize');

            $.get('{{route("category.rank")}}?'+rank, function(response){

                $('.card-header').after('<div id="ordersuccess" class="alert alert-success rounded-0 py-1">Sıralama Güncellendi</div>');
                
                setTimeout(function(){
                    $("#ordersuccess").fadeOut();
                },2000);

            });
        }
    });



   });

</script>
@endpush

resources/views/dashboard/categories/show.blade.php
@extends('dashboard.layouts.master')
@section('content')
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Horizontal Form</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
   
        <div class="card-body">

            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input name="name" type="text" class="form-control" id="name"
                    value="{{$category->name}}">
                </div>
            </div>

            <div class="form-group row">
                <label for="parent" class="col-sm-2 col-form-label">Parent</label>
                <div class="col-sm-10">
                 <select class="form-control" name="parent" id="parent">
                    <option  <?php echo $category->parent==0 ? 'selected' : ''?> value="0">Üst Kategori</option>
                    @foreach($categories as $allcategory)
                    <option <?php echo  $category->parent==$allcategory->id ? 'selected' : ''?> value="{{$allcategory->id}}" >{{$allcategory->name}}</option>
                    @endforeach

                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                <textarea name="description" type="text" class="form-control" id="description"
                value="">{{$category->description}}</textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="parent" class="col-sm-2 col-form-label">Durum</label>
            <div class="col-sm-10">
             <select class="form-control" name="status" id="status">
                <option value="0" <?php echo $category->status==0 ? 'selected' : ''?> >Pasif</option>
                <option value="1" <?php echo $category->status==1 ? 'selected' : ''?> >Aktif</option>

            </select>
        </div>
    </div>

</div>
<!-- /.card-body -->
<div class="card-footer">
    <button type="submit" class="btn btn-info">Create</button>
    <a href="{{route('category.index')}}" type="button" class="btn btn-default float-right">Cancel</a>
</div>
<!-- /.card-footer -->
</form>
</div>

@endsection